### ISSUE TITLE
when called with "--out-format turtle" causes a NPE

### ISSUE THREAD

**Issue by egonw** [tkuhn/npop#1]
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at info.aduna.lang.service.ServiceRegistry.get(ServiceRegistry.java:106)
        at org.openrdf.rio.Rio.createWriter(Rio.java:251)
        at org.petapico.npop.Extract.run(Extract.java:104)
        at org.petapico.npop.Extract.main(Extract.java:71)

**Comment by tkuhn** [comment]
Should work with the latest commit (and use "ttl" instead of "turtle").
